import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUiProviders } from "@/providers/NextUiProvider";
import { StoreProvider } from "@/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`bg-[#010624] min-h-[100vh]${inter.className}`}>
        <StoreProvider>
          <NextUiProviders>{children}</NextUiProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
